name: Run Node Script

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-on-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4 # استفاده از نسخه جدیدتر
        with:
          node-version: '20' # مشخص کردن نسخه نود جی

      - name: Install dependencies and Run script
        run: |
          npm install
          node index.js

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4 # استفاده از نسخه جدیدتر برای سرعت و پایداری بیشتر
        with:
          name: get-cookiestxt-locally
          path: extensions/get-cookiestxt-locally.crx