name: Run Python Script Every 5 Minutes

on:
  push:
    branches: [ "main" ]
  # schedule:
  #   # این خط اسکریپت را هر 5 دقیقه یکبار اجرا می‌کند
  #   - cron: '*/59 * * * *'
  workflow_dispatch: # برای اینکه بتوانید دستی هم تست کنید



jobs:
  run-on-linux:
    # استفاده از آخرین نسخه لینوکس اوبونتو
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-node@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          npm i
          node index.js

      - name: Upload extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: get-cookiestxt-locally
          path: extensions/get-cookiestxt-locally.crx
          # یا اگر می‌خواهید پوشه کامل را آپلود کنید:
          # path: extensions/


      - name: Run my script
        run: node index.js
      